--
-- PostgreSQL database dump
--

\restrict UthHJx20Ko6LCW2vLeolFs3fZ8m5G4XGfSU8PWrPHPEnD2a5483FxXygqkIet6p

-- Dumped from database version 16.10 (Ubuntu 16.10-1.pgdg24.04+1)
-- Dumped by pg_dump version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: bmw; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA bmw;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: django_migrations; Type: TABLE; Schema: bmw; Owner: -
--

CREATE TABLE bmw.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: bmw; Owner: -
--

ALTER TABLE bmw.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bmw.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_backupjob; Type: TABLE; Schema: bmw; Owner: -
--

CREATE TABLE bmw.services_backupjob (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    db_type character varying(20) NOT NULL,
    db_name character varying(100) NOT NULL,
    db_host character varying(200) NOT NULL,
    db_port integer NOT NULL,
    db_user character varying(100) NOT NULL,
    db_password character varying(300) NOT NULL,
    schedule_type character varying(100) NOT NULL,
    schedule_time time without time zone,
    keep_last integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: services_backupjob_id_seq; Type: SEQUENCE; Schema: bmw; Owner: -
--

ALTER TABLE bmw.services_backupjob ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bmw.services_backupjob_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: bmw; Owner: -
--

COPY bmw.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-11-16 11:35:06.149482+01
2	contenttypes	0002_remove_content_type_name	2025-11-16 11:35:06.167346+01
3	auth	0001_initial	2025-11-16 11:35:06.189971+01
4	auth	0002_alter_permission_name_max_length	2025-11-16 11:35:06.20269+01
5	auth	0003_alter_user_email_max_length	2025-11-16 11:35:06.218626+01
6	auth	0004_alter_user_username_opts	2025-11-16 11:35:06.233489+01
7	auth	0005_alter_user_last_login_null	2025-11-16 11:35:06.244236+01
8	auth	0006_require_contenttypes_0002	2025-11-16 11:35:06.249986+01
9	auth	0007_alter_validators_add_error_messages	2025-11-16 11:35:06.261476+01
10	auth	0008_alter_user_username_max_length	2025-11-16 11:35:06.274793+01
11	auth	0009_alter_user_last_name_max_length	2025-11-16 11:35:06.290136+01
12	auth	0010_alter_group_name_max_length	2025-11-16 11:35:06.298765+01
13	auth	0011_update_proxy_permissions	2025-11-16 11:35:06.30349+01
14	auth	0012_alter_user_first_name_max_length	2025-11-16 11:35:06.312522+01
15	customers	0001_initial	2025-11-16 11:35:06.326917+01
16	admin	0001_initial	2025-11-16 11:35:06.34248+01
17	admin	0002_logentry_remove_auto_add	2025-11-16 11:35:06.357998+01
18	admin	0003_logentry_add_action_flag_choices	2025-11-16 11:35:06.371186+01
19	customers	0002_client_domain	2025-11-16 11:35:06.383414+01
20	sessions	0001_initial	2025-11-16 11:35:06.391554+01
21	services	0001_initial	2025-11-16 11:53:16.165487+01
\.


--
-- Data for Name: services_backupjob; Type: TABLE DATA; Schema: bmw; Owner: -
--

COPY bmw.services_backupjob (id, name, db_type, db_name, db_host, db_port, db_user, db_password, schedule_type, schedule_time, keep_last, is_active, created_at) FROM stdin;
6		postgres	backup_db	localhost	5432	postgres	zaza	manual	\N	5	t	2025-11-18 17:47:57.73581+01
\.


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: bmw; Owner: -
--

SELECT pg_catalog.setval('bmw.django_migrations_id_seq', 21, true);


--
-- Name: services_backupjob_id_seq; Type: SEQUENCE SET; Schema: bmw; Owner: -
--

SELECT pg_catalog.setval('bmw.services_backupjob_id_seq', 6, true);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: bmw; Owner: -
--

ALTER TABLE ONLY bmw.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: services_backupjob services_backupjob_pkey; Type: CONSTRAINT; Schema: bmw; Owner: -
--

ALTER TABLE ONLY bmw.services_backupjob
    ADD CONSTRAINT services_backupjob_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict UthHJx20Ko6LCW2vLeolFs3fZ8m5G4XGfSU8PWrPHPEnD2a5483FxXygqkIet6p

