# Generated by Django 4.2.3 on 2025-11-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_type', models.CharField(default='postgres', max_length=20)),
                ('db_name', models.CharField(max_length=100)),
                ('db_host', models.CharField(max_length=200)),
                ('db_port', models.IntegerField(default=5432)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=300)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual Only')], max_length=100)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('keep_last', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
