# Generated by Django 4.2.3 on 2025-11-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_dailyschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySchedule',
        ),
    ]
